### ISSUE TITLE
SimplePBR12 Xbox problems

### ISSUE THREAD

**Issue by iHateInventNames** [Microsoft/Xbox-ATG-Samples#1]
- it works extremely slow in debug mode under Xbox one.

- unlaunchable in release mode - exceptions

Xbox has installed updates

**Comment by iHateInventNames** [comment]
same with today VS update

**Comment by walbourn** [comment]
I'm assuming you are using UWP on Xbox rather than the Xbox One XDK. Since it's a DirectX 12 app, it shouldn't work at all since DirectX 12 is not currently supported for UWP on Xbox. If it 'work's on debug, it's likely using WARP12.

**Comment by walbourn** [comment]
Note that with the October 2017 Xbox One recovery, UWP on Xbox One will now support DirectX 12 with hardware *if* you set the application type to 'Game'. For retail submission, this is part of the Windows Store metadata. During development, this is done via DevHome.
