### ISSUE TITLE
Build errors on SimpleRaytracingTriangle_PC12 project

### ISSUE THREAD

**Issue by ShawnKendall** [Microsoft/Xbox-ATG-Samples#16]
I get a compile error, see output below. Looks like it's just the FallbackLayer and I'm guessing I haven't set something extra outside of the project. 
Thanks for any help!

1>------ Build started: Project: FallbackLayer, Configuration: Debug x64 ------
1>'PrebuildCheck.bat' is not recognized as an internal or external command,
1>operable program or batch file.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(128,5): error MSB3073: The command "cd "C:\Users\skendall\Downloads\Xbox-ATG-Samples-master\Xbox-ATG-Samples-master\Kits\D3D12RaytracingFallback\src\..\tools\x64\"
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(128,5): error MSB3073: PrebuildCheck.bat
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(128,5): error MSB3073: :VCEnd" exited with code 9009.
1>Done building project "FallbackLayer.vcxproj" -- FAILED.
2>------ Build started: Project: SimpleRaytracingTriangle_PC12, Configuration: Debug x64 ------
2>LINK : fatal error LNK1104: cannot open file 'C:\Users\skendall\Downloads\Xbox-ATG-Samples-master\Xbox-ATG-Samples-master\Kits\D3D12RaytracingFallback\Bin\x64\Debug\Output\FallbackLayer.lib'
2>Done building project "SimpleRaytracingTriangle_PC12.vcxproj" -- FAILED.
========== Build: 0 succeeded, 2 failed, 1 up-to-date, 0 skipped ==========

**Comment by walbourn** [comment]
Did you figure out what went wrong?

**Comment by ShawnKendall** [comment]
Actually no. But I ended up getting "DirectX-Graphics-Samples-master" ray tracing examples building instead, so I'm learning from those.
But honestly, the number of DX12 example projects (including ray tracing) posted by MS is confusing.

**Comment by walbourn** [comment]
Sorry, that was my fault. I've fixed the master branch for the missing files in [this commit](https://github.com/Microsoft/Xbox-ATG-Samples/commit/7731f1fc32cfbe5d8e91a837f7c1f76c323114ae) which will be included in the next formal release.

**Comment by ShawnKendall** [comment]
No problem! And thanks for the fix and link. And when is the next formal release?

**Comment by walbourn** [comment]
Likely in a week or two... I need to do releases for the DirectX Tool Kit, DirectXTex, etc. first.

**Comment by walbourn** [comment]
The fixes are in the [feb2019](https://github.com/Microsoft/Xbox-ATG-Samples/releases/tag/feb2019) release.
