### ISSUE TITLE
AO Sample Camera Change Fix

### ISSUE THREAD

**Issue by Fierykev** [microsoft/Xbox-ATG-Samples#18]
When the camera was altered from a y-axis rotation camera to a zoom based one, certain lines of the code were not changed to comply with the new projection to world matrix.

Specifically, line 83 in RaytracingAOPC12.cpp showing:
`m_sceneCB[frameIndex].projectionToWorld = XMMatrixInverse(nullptr, viewProj);`

Needs to be transposed as the entries are no longer symmetric:
`m_sceneCB[frameIndex].projectionToWorld = XMMatrixTranspose(XMMatrixInverse(nullptr, viewProj));`

Consequently, line 86 of AORaytracing.hlsl must be removed as it is no longer needed as a temporary fix:
`screenPos *= 20;`

Lastly, the readme seems to be missing information about the camera controls A and D for zooming in and out.

Cheers,
Kevin Pick

**Comment by walbourn** [comment]
Thanks for the report. I'll look at getting these updated.
