### ISSUE TITLE
uwp input interface

### ISSUE THREAD

**Issue by Rorschach1219** [microsoft/Xbox-ATG-Samples#21]
![screenshot](https://user-images.githubusercontent.com/20067002/71085098-af3b4500-21d1-11ea-9464-2cb10e0142d1.png)

uwp inputinterfaceSample ，Demo program does not work properly

**Comment by walbourn** [comment]
You appear to have opened just the vcxproj directly. You need to open open the sln which contains two projects. If you are having trouble with the sample browser ZIPs, you can clone the whole repo.

**Comment by Rorschach1219** [comment]
> 
> 
> You appear to have opened just the vcxproj directly. You need to open the sln which contains two projects. If you are having trouble with the sample browser ZIPs, you can clone the whole repo.

![图片](https://user-images.githubusercontent.com/20067002/71141754-231c3280-2250-11ea-9dff-697d5ccfea11.png)
I added directxtk to the solution as prompted, but the three. H files referenced by "include" did not load normally and were not displayed in the solution view

**Comment by Rorschach1219** [comment]
![图片](https://user-images.githubusercontent.com/20067002/71151635-312d7b80-226f-11ea-9177-59c6e6c51520.png)
![图片](https://user-images.githubusercontent.com/20067002/71151736-705bcc80-226f-11ea-9867-901ffe79c70f.png)

I've set the correct path for the project reference, but it still doesn't work.

**Comment by Rorschach1219** [comment]
@walbourn
