### ISSUE TITLE
Profiling Tools

### ISSUE THREAD

**Issue by MikeGameDev** [microsoft/Xbox-ATG-Samples#30]
Hi, 

I'm relatively new to UWP development on Xbox One and I'm wondering what kind of performance profiling tools are available for this platform. Is there something similar to the ETW system present on desktop Windows 10? 

Thanks

**Comment by walbourn** [comment]
I'm afraid there's no much support for graphics profiling with UWP on Xbox directly. On PC you can make use of the "new pix" for DirectX 12 work, and the VSTS graphic profiler for DirectX 11 is an option on PC as well.

On UWP on Xbox, I believe you can use the Visual Studio CPU profiler, but not the graphics debugging.

For UWP on Xbox, really your best bet is to optimize it on PC as best you can. For games, the 'Game Mode' gives you a good amount of hardware on UWP on Xbox, and without it you need the app to be really light-weight.

https://walbourn.github.io/directx-and-uwp-on-xbox-one/
