### ISSUE TITLE
The Windows SDK version 10.0.14393.0 was not found. 

### ISSUE THREAD

**Issue by omd24** [microsoft/Xbox-ATG-Samples#32]
I'm trying to build "SimpleMSAA_PC12" project but it doesn't work with any of my installed SDKs (10.0.19041.0, 10.0.18362.0, and 10.016299.0). From the looks of it (see image), VS installer doesn't have any options to install SDKs older than 10.016299.0, is there any way to install 10.0.14393.0 SDK? Is there any workaround to use later SDKs with the project?

![image](https://user-images.githubusercontent.com/74592722/125570727-b8d77b78-e6aa-4362-9b2f-a2e9a7984e5a.png)

**Comment by walbourn** [comment]
You can upgrade the project to a newer Windows SDK and toolset.

**Comment by omd24** [comment]
Thanks Chuck. Retargeting the solution solved the issue.   
I was only retargeting the project so that was probably what went wrong with my previous attempts.
