### ISSUE TITLE
RasterFontViewer only understands 1BPP depth.

### ISSUE THREAD

**Issue by nkrapivin** [microsoft/Xbox-ATG-Samples#33]
RasterFontViewer only understands 1BPP depth.

Anything else results to corrupted data.

**Comment by nkrapivin** [comment]
> Thanks for the report. The RasterFontGen and RasterFontViewer tools are specifically intended for the Xbox Development Kit "Front Panel Display" which is monochromatic.
> 
> I'm guessing you used `GRAY2`, `GRAY4`, and/or `GRAY8` with the RasterFontGen tool? I'm guessing that was never really more than a development experiment.

Yeah... I had to peek at BMFont's source code, but this was also helpful (in terms of glyph cell positioning)

Made my own GDI font renderer: https://pastebin.com/N9JuFeuy

**Comment by walbourn** [comment]
The code in RasterFontGen can capture both 'TrueType' and older style "Raster" fonts. I've got a work item on my backlog to add support for capturing 'raster' fonts to *DirectX Tool Kit*'s [MakeSpriteFont](https://github.com/microsoft/DirectXTK/tree/master/MakeSpriteFont) tool. Most cases are best served with TrueType fonts, but for the very small Xbox Front Panel display, raster fonts are needed for easy reading.
