### ISSUE TITLE
DX::ReadData - paths issue ?

### ISSUE THREAD

**Issue by DTL2020** [microsoft/Xbox-ATG-Samples#35]
I use DX::ReadData() function to load shader .cso file (as from sample SimpleCompute - https://github.com/microsoft/Xbox-ATG-Samples/blob/9654b6efa4e1db52365fc2ae80386e0e27b9658d/UWPSamples/IntroGraphics/SimpleComputeUWP/SimpleComputeUWP.cpp#L337 ).
It is from file https://github.com/microsoft/Xbox-ATG-Samples/blob/9654b6efa4e1db52365fc2ae80386e0e27b9658d/Kits/ATGTK/ReadData.h

I not experience any issues at development Windows10 machine. But with release version users start to complain on Unhandled C++ exception crash at startup.

I add exception handler around DX::ReadData() call:

 ```
// load compute shader
  std::vector<uint8_t> computeShaderBlob;
  try {
    computeShaderBlob = DX::ReadData(L"Compute.cso");
  }
  catch (std::exception& e)
  {
    env->ThrowError(
      "MAnalyse: Can not load file Compute.cso %s", e.what()
    ); 
  }
```

And users report error: 
MAnalyse: Can not load file Compute.cso ReadData 
(https://forum.doom9.org/showthread.php?p=1962099#post1962099 )

The solution at user-side was mostly like to place compiled executable (.dll and launching .exe and compute.cso) in some simple path like c:\AVS and it works. The non-working path may be some like c:\plugins64+ . Can the + char cause some error in function ReadData ? Can ReadData return more detailed error about what is happens ? May I not right use e.what() method of return error description ?

**Comment by walbourn** [comment]
The ``DX::ReadData`` helper looks in the current working directory at runtime for the file.

When building for Win32 desktop, if it can't find it there, then it looks in the same folder as the running EXE. If you are a 'plugin' then likely that directory where you have your plug in installed.

Your best option is to use some full path to your "plugin" directory to find your data and not rely on CWD.
