### ISSUE TITLE
Dependancies?

### ISSUE THREAD

**Issue by Ianuarius** [microsoft/Xbox-ATG-Samples#39]
Is there any documentation anywhere about the dependancies? I cannot get this to compile no matter what I do. Just 1000+ errors.

What do I need to do to get any of the WinRT samples to compile on VS2022? I didn't imagine not getting anywhere when I tried to access any of the samples. I got thrown to the samples page and thought "oh, cool! I can test some stuff out." Nope. No documentation. Nothing. Just stop and go do something else. I feel like there's something vital missing there.

**Comment by walbourn** [comment]
Which samples are you building in particular?

**Comment by Ianuarius** [comment]
Hey, thanks for the reply.

I was trying to build the SimpleTriangleCppWinRT_UWP12 with the latest VS.

**Comment by walbourn** [comment]
OK. Currently all the samples are set to use VS 2017 per [the readme](https://github.com/microsoft/Xbox-ATG-Samples#uwp-apps).

The UWP samples can be built with VS 2019 or VS 2022 if you have the *Universal Windows Platform* workload installed plus the *C++ Tools for UWP apps* optional component installed *AND* you use the Visual Studio option *Retarget solution*.

> You can also build it without upgrading if you have the *Windows SDK (19041)* component -and- the "C++ Tools for UWP aps (V142)* optional component installed as well.

The PC samples can also be retargeted if you have the *Desktop development with C++* workload installed.

> The Xbox One XDK samples can't be upgraded to anything newer because the legacy Xbox One XDK does not support VS 2019 or VS 2022. Instead, use [XBox-GDK-Samples](https://github.com/microsoft/Xbox-GDK-Samples).

**Comment by Ianuarius** [comment]
Alright, thanks for the info.
