### ISSUE TITLE
FullscreenQuad not needed constant buffer 

### ISSUE THREAD

**Issue by amerkoleci** [Microsoft/Xbox-ATG-Samples#4]
I saw there is a constant buffer but no usage in shader under directx 12

**Comment by walbourn** [comment]
Thanks for the feedback!

it is true that the default pixel shader does not make use of any constants, but the FSQ root signature was defined to make it a bit more flexible. In particular, the SimpleHDR sample uses it in ``PrepareSwapChainBuffersPS.hlsl``.

For the DirectX 11 implementation, such 'additional parameters' are safely handled through the ``setCustomState``, but DirectX 12 root signatures are a lot less forgiving, particularly on Xbox One.

**Comment by amerkoleci** [comment]
Thanks for clarification.
