### ISSUE TITLE
Can you help compile "FlightStick" and provide a sideload package?

### ISSUE THREAD

**Issue by Vict0r-Chen** [microsoft/Xbox-ATG-Samples#42]
Can you help compile [FlightStick](https://github.com/microsoft/Xbox-ATG-Samples/tree/main/XDKSamples/System/FlightStick) and provide a sideload package?
For some reason, I can't compile this project, and the alternative [Xbox-GDK-Samples/Gamepad](https://github.com/microsoft/Xbox-GDK-Samples/tree/main/Samples/System/Gamepad) also won't compile, but I desperately need this feature for some test, I know it sounds a bit incomprehensible, but is it possible to do this?😢

**Comment by walbourn** [comment]
These are both Xbox One XDK samples, not UWP or PC.

**Comment by walbourn** [comment]
There is a UWP version of GamePad here: https://github.com/microsoft/Xbox-ATG-Samples/tree/main/UWPSamples/System/GamepadUWP

**Comment by Vict0r-Chen** [comment]
Hi Walbourn, thanks for your reply, you helped me a lot.

The [GamepadUWP](https://github.com/microsoft/Xbox-ATG-Samples/tree/main/UWPSamples/System/GamepadUWP) sample does work on my PC, but unfortunately this Sample doesn't recognize my FlightStick. Why doesn't FlightStick have a UWP or PC version of Samples? Is it because FlightStick is only supported on XBox?

In addition, does the "Xbox One Development Kit" refer to the prototype released by Microsoft after registering ID@XBox? Can I use XBox in developer mode instead?

Thanks again.

**Comment by Vict0r-Chen** [comment]
Hi @walbourn , thanks for your reply, you helped me a lot.

The [GamepadUWP](https://github.com/microsoft/Xbox-ATG-Samples/tree/main/UWPSamples/System/GamepadUWP) sample does work on my PC, but unfortunately this Sample doesn't recognize my FlightStick. Why doesn't FlightStick have a UWP or PC version of Samples? Is it because FlightStick is only supported on XBox?

In addition, does the "Xbox One Development Kit" refer to the prototype released by Microsoft after registering ID@XBox? Can I use XBox in developer mode instead?

Thanks again.

**Comment by walbourn** [comment]
I haven't checked in a while, but the Windows Gaming Input FlightStick support is limited to a few devices. The only sample on PC I'm aware of is the [docs](https://docs.microsoft.com/en-us/windows/uwp/gaming/flight-stick). The API should be similar to the Xbox One XDK sample.

**Comment by Vict0r-Chen** [comment]
Thanks dude, the example you mentioned I used before and it worked fine. 
But I wonder how the XDK example works? Is it similar to UWP application development, make the host enter developer mode and then use visual studio to remotely debug it on the PC?
