### ISSUE TITLE
SimpleBezierUWP not working correctly on Xbox Series X and S

### ISSUE THREAD

**Issue by invor** [microsoft/Xbox-ATG-Samples#45]
I tried to run the SimpleBezierUWP sample on Xbox Series X and S as a UWP game app (using retail consoles in devmode) and it is not working correctly. The rendered geometry simply won't show up in the viewport and no errors are logged on the debug console in Visual Studio. Investigating the problem a little bit using `D3D11_QUERY_DATA_PIPELINE_STATISTICS` revealed that the hull shader is still executed on the expected number of control points but no domain shader innvocations are recorded. From here on, I'm not sure how to debug this further. Is this a bug? Or is tessellation not supported on these devices and UWP?

**Comment by walbourn** [comment]
I saw your report on StackOverflow as well. I'm filing a bug with the graphics team.

**Comment by walbourn** [comment]
Can you try the DX12 version of the same sample?

**Comment by invor** [comment]
Thanks for the fast reply. It only occured to me after I had posted on StackOverflow that I might as well open an issue here closer to the source.

Regarding the DX12 version: SimpleBezierUWP12 behaves identically, but I can't offer any pipeline statistics for that version at the moment.

**Comment by walbourn** [comment]
I've reported the issue to the graphics team.
