### ISSUE TITLE
PIX for UWP games?

### ISSUE THREAD

**Issue by procedural** [Microsoft/Xbox-ATG-Samples#5]
Is it possible to profile a UWP game under Xbox Live Creators Program with PIX? I see some UWP examples are using it, but I can't find official docs on this.

Thanks!

**Comment by walbourn** [comment]
There's a new PIX, but it only works for DirectX 12. See [this blog post](https://blogs.msdn.microsoft.com/pix/).

Otherwise, you should be able to use the Visual Studio Graphics Diagnostics (a.k.a. VSPIX).

**Comment by procedural** [comment]
Thanks! Is there any quick how-to guide on profiling my DirectX 12 UWP app on Xbox from a Windows PC remotely?

**Comment by walbourn** [comment]
Apparently it doesn't support UWP on Xbox One either :(

VSGS debugging is about all you can get, although you can do profiling on PC with the "new PIX"

**Comment by procedural** [comment]
Oh, no wonder I couldn't find info on this! Thanks anyway, @walbourn!
