### ISSUE TITLE
Xbox doesn't log in

### ISSUE THREAD

**Issue by skanda890** [microsoft/Xbox-ATG-Samples#53]
It said this while I was trying to log in. I tried restarting my PC but nothing changed. I reinstalled Xbox also but still nothing changed.
![image](https://github.com/microsoft/Xbox-ATG-Samples/assets/99239826/a86b5d8e-9449-4fe7-b664-993ef4f5b510)

**Comment by skanda890** [comment]
What should I do to make this go away?

**Comment by skanda890** [comment]
Is this the right repository to report this issue? If not, then which one I couldn't find any other repository.

**Comment by walbourn** [comment]
Are you using "DevMode" on a retail Xbox kit or are you using an Xbox Developer Kit?

**Comment by skanda890** [comment]
I am using a PC.

**Comment by walbourn** [comment]
Are you back developer using the GDK?

https://learn.microsoft.com/en-us/gaming/gdk/_content/gc/live/test-release/troubleshooting/live-troubleshoot-sandboxes

**Comment by skanda890** [comment]
Okay, I will try that and let you know.

**Comment by skanda890** [comment]
I didn't know what to do on that website.

**Comment by skanda890** [comment]
Didn't get it.
