### ISSUE TITLE
Question: explicit control of ESRAM?

### ISSUE THREAD

**Issue by procedural** [Microsoft/Xbox-ATG-Samples#6]
Is it possible to explicitly control DirectX 12 resource residency by moving textures or buffers to / from ESRAM? I think I can assume that in certain cases Xbox will move stuff for me implicitly, but if I want a specific piece of data stay there I need some form of explicit control. Is there any info / documentation on that or it's not even possible? (context: I'm under Xbox Live Creators program)

**Comment by walbourn** [comment]
UWP on Xbox One does not expose explicit control of ESRAM. It's also important to note that ESRAM doesn't exist on the Xbox One X--it has faster standard memory instead.

**Comment by procedural** [comment]
Thank you for clarification!

**Comment by procedural** [comment]
Vulkan solves this quite elegantly by allowing to query available memory types and allocating from whichever suits your needs...
